using System;

namespace Com.Coppel.SDPC.Core.Carteras;

public partial class CarCifraControlOperacion
{
	public DateTime FechaMovimiento { get; set; }
	public DateTime FechaCorte { get; set; }
	public byte NumeroCarga { get; set; }
	public string Clave { get; set; } = null!;
	public long? VentasClientesRopa { get; set; }
	public long? ContadosClientesRopa { get; set; }
	public long? EnganchesClientesRopa { get; set; }
	public long? AbonosClientesRopa { get; set; }
	public int? BonificacionClientesRopa { get; set; }
	public int? VentasEmpleadosRopa { get; set; }
	public int? ContadosEmpleadosRopa { get; set; }
	public int? EnganchesEmpleadosRopa { get; set; }
	public int? AjustesClientesRopa { get; set; }
	public int? ReembolsosClientesRopa { get; set; }
	public int? ReembolsosEmpleadosRopa { get; set; }
	public int? MovtosNoActualizadosRopa { get; set; }
	public int? VentasMueblesRecio { get; set; }
	public int? EnganchesMueblesRecio { get; set; }
	public long? SaldoFinalRopa { get; set; }
	public int? VentaSegurosVida { get; set; }
	public int? InteresCobradoRopa { get; set; }
	public int? InteresCargadoRopa { get; set; }
	public int? InteresCanceladoRopa { get; set; }
	public int? InteresNoActualizadoRopa { get; set; }
	public long? SaldoInteresRopa { get; set; }
	public int? EtpRopa { get; set; }
	public long? VentasClientesMuebles { get; set; }
	public long? ContadosClientesMuebles { get; set; }
	public long? EnganchesClientesMuebles { get; set; }
	public long? AbonosClientesMuebles { get; set; }
	public int? BonificacionClientesMuebles { get; set; }
	public int? VentasEmpleadosMuebles { get; set; }
	public int? ContadosEmpleadosMuebles { get; set; }
	public int? EnganchesEmpleadosMuebles { get; set; }
	public int? AjustesClientesMuebles { get; set; }
	public int? ReembolsosClientesMuebles { get; set; }
	public int? ReembolsosEmpleadosMuebles { get; set; }
	public int? MovtosNoActualizadosMuebles { get; set; }
	public int? DevolucionClientesMuebles { get; set; }
	public int? DevolucionEmpleadosMuebles { get; set; }
	public int? DevolucionMueblesSaldarRopa { get; set; }
	public long? SaldoFinalMuebles { get; set; }
	public int? InteresCobradoMuebles { get; set; }
	public int? InteresCargadoMuebles { get; set; }
	public int? InteresCanceladoMuebles { get; set; }
	public int? InteresNoActualizadoMuebles { get; set; }
	public long? SaldoInteresMuebles { get; set; }
	public int? EtpMuebles { get; set; }
	public int? AltasDirectorio { get; set; }
	public int? CambiosDirectorio { get; set; }
	public int? ReposicionesDirectorio { get; set; }
	public int? AltasPorVentasDirectorio { get; set; }
	public int? AltasPorCambiosDirectorio { get; set; }
	public int? MovtosNoActDirectorio { get; set; }
	public int? AltasSolicitudes { get; set; }
	public int? CambiosSolicitudes { get; set; }
	public int? AltasPorCambiosSolicitudes { get; set; }
	public int? InventarioDomicilio { get; set; }
	public int? MovtosNoActInventarioDom { get; set; }
	public int? CobranzaTelefonica { get; set; }
	public int? MovtosNoActCobranzaTel { get; set; }
	public int? BajasSolicitudes { get; set; }
	public int? BajasSegurosVida { get; set; }
	public int? BajasInventarioDomicilio { get; set; }
	public int? RegistrosDirectorio { get; set; }
	public int? RegistrosSolicitudes { get; set; }
	public int? MovtosNoActSolicitudes { get; set; }
	public int? RegistrosSegurosVida { get; set; }
	public int? RegistrosInventarioDomicilio { get; set; }
	public int? RegistrosCobranzaTel { get; set; }
	public string? MarcaCargado { get; set; }
	public long? PrestamoDinero { get; set; }
	public long? AbonoPrestamo { get; set; }
	public long? BonificacionPrestamo { get; set; }
	public long? LiquidacionPrestamo { get; set; }
	public long? InteresesPrestamo { get; set; }
	public int? ConveniosPrestamo { get; set; }
	public int? VentasClientesTiempoAire { get; set; }
	public int? ContadosClientesTiempoAire { get; set; }
	public int? EnganchesClientesTiempoAire { get; set; }
	public int? VentasEmpleadosTiempoAire { get; set; }
	public int? ContadosEmpleadosTiempoAire { get; set; }
	public int? EnganchesEmpleadosTiempoAire { get; set; }
	public long? SaldoFinalPrestamos { get; set; }
	public int? MovtosNoActPrestamo { get; set; }
	public int? BonificacionAutomaticaMensualPrestamos { get; set; }
	public int? SaldoRojoMensualPrestamos { get; set; }
	public long? InteresCargadoMensualPrestamos { get; set; }
	public int? InteresCanceladoMensualPrestamos { get; set; }
	public long? ImporteNoActSegurosVida { get; set; }
	public long? MovNoActSegurosVida { get; set; }
	public int? PagosSegurosVida { get; set; }
	public long? SaldoFinalPrestamos20Anterior { get; set; }
	public long? SaldoFinalRopa20Anterior { get; set; }
	public int? BonificacionAutomaticaMensualRopa { get; set; }
	public int? SaldoRojoMensualRopa { get; set; }
	public int? InteresCargadoMensualRopa { get; set; }
	public int? InteresCanceladoMensualRopa { get; set; }
	public long? SaldoFinalMuebles20Anterior { get; set; }
	public int? BonificacionAutomaticaMensualMuebles { get; set; }
	public int? AjustesClientesPrestamos { get; set; }
	public int? InteresNoActualizadoPrestamos { get; set; }
	public int? AjustesSeguroVida { get; set; }
	public int? AjustesInventarioDomicilio { get; set; }
	public int? AjustesSolicitudes { get; set; }
	public long? SaldoFinalTiempoAire { get; set; }
	public long? SaldoInteresTiempoAire { get; set; }
	public int? AjustesClientesCancIntPrestamos { get; set; }
	public int? VentaCteTa { get; set; }
	public int? VentaCteContadoTa { get; set; }
	public int? VentaEngancheCteTa { get; set; }
	public int? VentaEmpTa { get; set; }
	public int? VentaEmpContadoTa { get; set; }
	public int? VentaEngancheEmpTa { get; set; }
	public int? AbonosTa { get; set; }
	public int? BonificacionTa { get; set; }
	public int? ConvenioTa { get; set; }
	public int? ReembolsoTa { get; set; }
	public int? PagoInteresTa { get; set; }
	public int? AjustesTa { get; set; }
	public int? AjustesCanclntTa { get; set; }
	public string AltasAfore { get; set; } = null!;
	public long? DeudaBancoppel { get; set; }
	public long? AbonoDeudaBancoppel { get; set; }
	public int? BonificacionDeudaBancoppel { get; set; }
	public long? InteresAdicionalDeudaBancoppel { get; set; }
	public int? ConvenioDeudaBancoppel { get; set; }
	public int? AjustesDeudaBancoppel { get; set; }
	public int? AjustesCancIntBancoppel { get; set; }
	public long? SaldoFinalDeudaBancoppel { get; set; }
	public int? SaldoRojoMensualDeudaBancoppel { get; set; }
	public int? BonificacionAutomaticaMensualDeudaBancoppel { get; set; }
	public long? SaldoFinalDeudaBancoppel20Anterior { get; set; }
	public int? MovtosNoActDeudaBancoppel { get; set; }
	public int? InteresCobradoDeudaBancoppel { get; set; }
	public int? InteresCargadoDeudaBancoppel { get; set; }
	public int? InteresCanceladoDeudaBancoppel { get; set; }
	public int? InteresNoActualizadoDeudaBancoppel { get; set; }
	public long? SaldoInteresDeudaBancoppel { get; set; }
	public int? AbonoCreditoYcasa { get; set; }
	public long? ConveniosCreditoyCasa { get; set; }
	public int? CambiosCreditoyCasa { get; set; }
	public long? SaldoCyC { get; set; }
	public int? RegistrosCyC { get; set; }
	public int? AltasUh { get; set; }
	public int? MovtosNoActualizadosUh { get; set; }
	public int? RegistrosUh { get; set; }
	public long? MovtosNoActTa { get; set; }
	public long? InteresCobradoTa { get; set; }
	public long? InteresCargadoTa { get; set; }
	public long? InteresCanceladoTa { get; set; }
	public long? InteresNoActualizadoTa { get; set; }
	public long? BonificacionAutomaticaTa { get; set; }
	public long? SaldoRojoMensualTa { get; set; }
	public long? SaldoFinalTa20anterior { get; set; }
	public long? AjustesReestRopa { get; set; }
	public long? AjustesReestMuebles { get; set; }
	public long? AjustesReestPtmos { get; set; }
	public long? AjustesReestTa { get; set; }
	public long? AjustesIntReestRopa { get; set; }
	public long? AjustesIntReestMuebles { get; set; }
	public long? AjustesIntReestPtmos { get; set; }
	public long? AjustesIntReestTa { get; set; }
	public long? VentasReestructura { get; set; }
	public long? AbonoReestructura { get; set; }
	public long? BonificacionReestructura { get; set; }
	public long? AjustesReestructura { get; set; }
	public long? BonificacionAutomaticaMensualReest { get; set; }
	public long? MovtosNoActReestructura { get; set; }
	public long? SaldoFinalReestructura { get; set; }
	public long? SaldoFinalReestructura20Anterior { get; set; }
	public long? ConvenioReestructura { get; set; }
	public long? SaldoRojoMensualReestructura { get; set; }
	public long? IntCobradoReestructura { get; set; }
	public long? IntCargadoReestructura { get; set; }
	public long? IntCanceladoReestructura { get; set; }
	public long? IntNoActReestructura { get; set; }
	public long? SaldoInteresesReestructura { get; set; }
	public int? AjusteCanclntReestructura { get; set; }
	public int? GanoDineroElectronico { get; set; }
	public int? GastoDineroElectronico { get; set; }
	public long? Saldodineroelectronico { get; set; }
	public int? CobroEmpleadosRopa { get; set; }
	public int? PlanesMovistar { get; set; }
	public int? CorreoDevueltoAfore { get; set; }
	public int? AjusteAbonoBincRopa { get; set; }
	public int? AjusteAbonoBincMuebles { get; set; }
	public int? AjusteAbonoBincPrestamos { get; set; }
	public int? AjusteAbonoBincTa { get; set; }
	public int? AjusteAbonoBincBanCoppel { get; set; }
	public int? AjusteCambPuntualidad { get; set; }
	public int? AjusteRecalculoDevParcial { get; set; }
	public int? AjusteRePrestamo { get; set; }
	public int? AjusteCambPlazo { get; set; }
	public int? VentasClientesNegocios { get; set; }
	public int? ContadosClientesNegocios { get; set; }
	public int? EnganchesClientesNegocios { get; set; }
	public int? VentasEmpleadosNegocios { get; set; }
	public int? ContadosEmpleadosNegocios { get; set; }
	public int? EnganchesEmpleadosNegocios { get; set; }
	public int? AbonosClientesNegocios { get; set; }
	public int? BonificacionClientesNegocios { get; set; }
	public int? ReembolsosClientesNegocios { get; set; }
	public int? ReembolsosEmpleadosNegocios { get; set; }
	public int? AjustesClientesNegocios { get; set; }
	public int? MovtosNoActNegocios { get; set; }
	public int? BonificacionAutomaticaNegocios { get; set; }
	public int? SaldoFinalNegocios { get; set; }
	public int? AjustesCancIntNegocios { get; set; }
	public int? InteresCobradoNegocios { get; set; }
	public int? InteresCargadoNegocios { get; set; }
	public int? InteresCanceladoNegocios { get; set; }
	public int? InteresNoActNegocios { get; set; }
	public int? SaldoInteresNegocios { get; set; }
	public int? AjusteAbonoBincNegocios { get; set; }
	public int? VentaSegurosAutos { get; set; }
	public int? PagosSegurosAutos { get; set; }
	public int? BajasSegurosAutos { get; set; }
	public long? RegistrosSegurosAutos { get; set; }
	public int? AjustesSeguroAutos { get; set; }
	public int? NumDepositosCorresp { get; set; }
	public long? ImpDepositosCorresp { get; set; }
	public int? NumPagosCorresp { get; set; }
	public int? ImpPagosCorresp { get; set; }
	public int? NumTransfCorresp { get; set; }
	public long? ImpTransfCorresp { get; set; }
	public int? AltasSolcAltaUnica { get; set; }
	public int? CambiosSolcAltaUnica { get; set; }
	public int? AltasxCambiosSolcAltaUnica { get; set; }
	public int? BajasSolcAltaUnica { get; set; }
	public int? RegistrosAltaUnica { get; set; }
	public int? MovNoActSolcAltaUnica { get; set; }
	public int? AjustesReestNegocios { get; set; }
	public int? AjustesIntReestNegocios { get; set; }
	public int? AjustesReestDeudaBcpl { get; set; }
	public int? AjustesIntReestDeudaBcpl { get; set; }
	public int NumAltasprospecto { get; set; }
	public int NumVtasSegbcpl { get; set; }
	public int ImpPagovtassegbcpl { get; set; }
	public int ImpAbonovtassegbcpl { get; set; }
	public int NumAltasbeneficiarios { get; set; }
	public int? NumMovsituacionesmarcarcte { get; set; }
	public int? NumMovsituacionesdesmarcarcte { get; set; }
	public int? NumMovsituacionesnoactcte { get; set; }
	public int? NumRegistrossituacionescte { get; set; }
	public int? NumMovsituacionesmarcarsol { get; set; }
	public int? NumMovsituacionesdesmarcarsol { get; set; }
	public int? NumMovsituacionesnoactsol { get; set; }
	public int? NumRegistrossituacionessol { get; set; }
	public int? NumMovcatsituaciones { get; set; }
	public int? NumMovreglasituaciones { get; set; }
	public int? NumMovcambiosctesituacion { get; set; }
	public int? NumMovmarcadoctesituacioninterno { get; set; }
	public int? NumMovdesmarcadoctesituacioninterno { get; set; }
	public int? NumMovcambiossolsituacion { get; set; }
	public int? NumMovmarcadosolsituacioninterno { get; set; }
	public int? NumMovdesmarcadosolsituacioninterno { get; set; }
	public long NumMovmarcadosolsituacionau { get; set; }
	public long NumMovdesmarcadosolsituacionau { get; set; }
	public long NumMovsituacionesnoactsolau { get; set; }
	public long NumMovcambiossolsituacionau { get; set; }
	public long NumMovregistrossolsituacionau { get; set; }
	public int NumConsultasaldoTc { get; set; }
	public int NumConsultasaldoTd { get; set; }
	public int NumRetirosTc { get; set; }
	public long? ImpRetirosTc { get; set; }
	public int NumRetirosTd { get; set; }
	public int ImpRetirosTd { get; set; }
	public int NumPagosTcconcargoTd { get; set; }
	public int ImpPagosTcconcargoTd { get; set; }
	public int NumTraspasosTd { get; set; }
	public int ImpTraspasosTd { get; set; }
	public int NumPagoTc { get; set; }
	public int ImpPagoTc { get; set; }
	public int NumPagoTcconcargoTd { get; set; }
	public int ImpPagoTcconcargoTd { get; set; }
	public long NumCancelacionesctes { get; set; }
	public long NumCancelacionesref { get; set; }
	public long NumCancelacionessol { get; set; }
	public long NumOposicionesctes { get; set; }
	public long NumOposicionesref { get; set; }
	public long NumOposicionessol { get; set; }
	public int? ImpBonificacionRefacturacion { get; set; }
	public long? ImpInteresRefacturacion { get; set; }
	public long? NumVentasproteccionsalud { get; set; }
	public long? ImpVentasproteccionsalud { get; set; }
	public long? NumAbonosproteccionsalud { get; set; }
	public long? ImpAbonosproteccionsalud { get; set; }
	public long? NumBeneficiariosproteccionsalud { get; set; }
	public long? ImpBeneficiariosproteccionsalud { get; set; }
	public long? NumAdicionalesproteccionsalud { get; set; }
	public long? ImpAdicionalesproteccionsalud { get; set; }
	public long? NumPolizasproteccionsalud { get; set; }
	public long? ImpPolizasproteccionsalud { get; set; }
	public long? NumCancadicionalesproteccionsalud { get; set; }
	public long? ImpCancadicionalesproteccionsalud { get; set; }
	public long? NumFinalseguroscps { get; set; }
	public long? NumSeguroscanceladoscps { get; set; }
	public long? NumSegurosdepuradoscps { get; set; }
	public long? NumAltasporabonosseguroscps { get; set; }
	public long ImpTarjetascontenido { get; set; }
	public long ImpTarjetascontenidoemp { get; set; }
	public long ImpDevolucionTarjetaContenidoActivas { get; set; }
	public long ImpDevolucionTarjetaContenidoInactivas { get; set; }
	public int NumAltasporcambioscoppel { get; set; }
	public int NumAltasporcambiosau { get; set; }
	public long ImpIntcondonadoRopa { get; set; }
	public long ImpIntcondonadoMuebles { get; set; }
	public long ImpIntcondonadoPrestamos { get; set; }
	public long ImpIntcondonadoTa { get; set; }
	public long ImpIntcondonadoRevolvente { get; set; }
	public long NumIntcondonadoRopa { get; set; }
	public long NumIntcondonadoMuebles { get; set; }
	public long NumIntcondonadoPrestamos { get; set; }
	public long NumIntcondonadoTa { get; set; }
	public long NumIntcondonadoRevolvente { get; set; }
	public int NumTotalMigraciones { get; set; }
	public int? ImpDevolucionesrevolvente { get; set; }
}
