namespace Com.Coppel.SDPC.Application.Models.Enums;

public enum FuncionalidadTypeVM
{
	SMLC = 1,
	SMCP = 2,
	DECREMENTO_LINEA_CREDITO = 3,
	TDI_CP = 4,
	TDI_CPC= 5,
	TDI_MORATORIO_CARTERA = 6,
	TDI_MORATORIO_DCP = 7,
	FACTORES_SATURACION_CARTERA = 8,
	TDI_CPPRESTAMO = 9,
	BONIFICACIONES = 10,
	CONVERSION_LINEA_CREDITO = 11,
	ASIGNACION_LINEAS = 12,
	ASIGNACION_GRUPO = 13
}
